# Generated by Django 3.1 on 2020-10-05 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=70)),
                ('nickname', models.CharField(max_length=70)),
                ('sex', models.CharField(max_length=70)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=150)),
            ],
        ),
    ]
