# Generated by Django 3.1 on 2020-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
            ],
        ),
    ]
