# Generated by Django 3.1 on 2020-09-01 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='account',
            name='pw',
            field=models.CharField(max_length=70),
        ),
    ]
