# Generated by Django 3.1 on 2020-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20200901_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcheck',
            name='code',
            field=models.IntegerField(max_length=70),
        ),
    ]
