# Generated by Django 3.1 on 2020-09-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_auto_20200901_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
    ]
