# Generated by Django 3.1 on 2020-09-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_auto_20200913_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
    ]
