# Generated by Django 3.1 on 2020-10-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
        migrations.CreateModel(
            name='TopLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
        migrations.CreateModel(
            name='OuterThin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
        migrations.CreateModel(
            name='OuterThick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
        migrations.CreateModel(
            name='BottomShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
        migrations.CreateModel(
            name='BottomLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
    ]
