# Generated by Django 3.1 on 2020-10-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomlong',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='bottomlong',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='outerthick',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='outerthick',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='toplong',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='toplong',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='topshort',
            name='descript',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='topshort',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('color', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=70)),
                ('descript', models.CharField(max_length=70, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.account')),
            ],
        ),
    ]
