# Generated by Django 3.1 on 2020-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20201012_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomlong',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bottomshort',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='dress',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='outerthick',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='outerthin',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='toplong',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='topshort',
            name='brand',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
