# Generated by Django 3.1 on 2020-10-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20201012_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottomlong',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='bottomshort',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='dress',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='outerthick',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='outerthin',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='toplong',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='topshort',
            old_name='category',
            new_name='subcategory',
        ),
    ]
