# Generated by Django 3.1 on 2020-10-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20201014_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomlong',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dress',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='outerthick',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='toplong',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='topshort',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
