# Generated by Django 3.1 on 2020-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_auto_20201102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerthick',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outerthick',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toplong',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toplong',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
    ]
