# Generated by Django 3.1 on 2020-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20201102_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomlong',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottomlong',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topshort',
            name='brand',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topshort',
            name='descript',
            field=models.CharField(blank=True, default='null', max_length=70),
            preserve_default=False,
        ),
    ]
