# Generated by Django 3.1 on 2020-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_auto_20201102_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomlong',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='bottomshort',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='dress',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='outerthick',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='outerthin',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='toplong',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='topshort',
            name='like',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
