# Generated by Django 3.1 on 2020-11-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20201117_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomlong',
            name='like',
        ),
        migrations.RemoveField(
            model_name='bottomshort',
            name='like',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='like',
        ),
        migrations.RemoveField(
            model_name='outerthick',
            name='like',
        ),
        migrations.RemoveField(
            model_name='outerthin',
            name='like',
        ),
        migrations.RemoveField(
            model_name='toplong',
            name='like',
        ),
        migrations.RemoveField(
            model_name='topshort',
            name='like',
        ),
    ]
