# Generated by Django 3.1 on 2020-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_auto_20201118_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomlong',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bottomshort',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dress',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outerthick',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outerthin',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toplong',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topshort',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
