# Generated by Django 3.1 on 2020-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancampus',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancampus',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mancasual',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mandandy',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manformal',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manminimal',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mansports',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manstreet',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantravel',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wocasual',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wofeminine',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woformal',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wogirlish',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='woromantic',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wosports',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wostreet',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='bottom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='bottomcol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='imgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='outer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='outercol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='top',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wotravel',
            name='topcol',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
