# Generated by Django 3.1 on 2020-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0002_auto_20201008_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancampus',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mancampus',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mancasual',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mancasual',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mandandy',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mandandy',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manformal',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manformal',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manminimal',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manminimal',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mansports',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mansports',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manstreet',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manstreet',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mantravel',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mantravel',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wocasual',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wocasual',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wofeminine',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wofeminine',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='woformal',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='woformal',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wogirlish',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wogirlish',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='woromantic',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='woromantic',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wosports',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wosports',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wostreet',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wostreet',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wotravel',
            name='dress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wotravel',
            name='dresscol',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
