# Generated by Django 3.1 on 2020-10-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0003_auto_20201010_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manunique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manworkwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wocampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wodandy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wominimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wounique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Woworkwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer', models.CharField(max_length=30, null=True)),
                ('outercol', models.CharField(max_length=30, null=True)),
                ('top', models.CharField(max_length=30, null=True)),
                ('topcol', models.CharField(max_length=30, null=True)),
                ('bottom', models.CharField(max_length=30, null=True)),
                ('bottomcol', models.CharField(max_length=30, null=True)),
                ('dress', models.CharField(max_length=30, null=True)),
                ('dresscol', models.CharField(max_length=30, null=True)),
                ('imgurl', models.CharField(max_length=100)),
            ],
        ),
    ]
