# Generated by Django 3.1 on 2020-10-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0005_auto_20201014_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mancampus',
            new_name='Mcampus',
        ),
        migrations.RenameModel(
            old_name='Mancasual',
            new_name='Mcasual',
        ),
        migrations.RenameModel(
            old_name='Mandandy',
            new_name='Mdandy',
        ),
        migrations.RenameModel(
            old_name='Manformal',
            new_name='Mformal',
        ),
        migrations.RenameModel(
            old_name='Manminimal',
            new_name='Mminimal',
        ),
        migrations.RenameModel(
            old_name='Mansports',
            new_name='Msports',
        ),
        migrations.RenameModel(
            old_name='Manstreet',
            new_name='Mstreet',
        ),
        migrations.RenameModel(
            old_name='Mantravel',
            new_name='Mtravel',
        ),
        migrations.RenameModel(
            old_name='Manunique',
            new_name='Munique',
        ),
        migrations.RenameModel(
            old_name='Manworkwear',
            new_name='Mworkwear',
        ),
        migrations.RenameModel(
            old_name='Wocampus',
            new_name='Wcampus',
        ),
        migrations.RenameModel(
            old_name='Wocasual',
            new_name='Wcasual',
        ),
        migrations.RenameModel(
            old_name='Wodandy',
            new_name='Wdandy',
        ),
        migrations.RenameModel(
            old_name='Wofeminine',
            new_name='Wfeminine',
        ),
        migrations.RenameModel(
            old_name='Woformal',
            new_name='Wformal',
        ),
        migrations.RenameModel(
            old_name='Wogirlish',
            new_name='Wgirlish',
        ),
        migrations.RenameModel(
            old_name='Wominimal',
            new_name='Wminimal',
        ),
        migrations.RenameModel(
            old_name='Woromantic',
            new_name='Wromantic',
        ),
        migrations.RenameModel(
            old_name='Wosports',
            new_name='Wsports',
        ),
        migrations.RenameModel(
            old_name='Wostreet',
            new_name='Wstreet',
        ),
        migrations.RenameModel(
            old_name='Wotravel',
            new_name='Wtravel',
        ),
        migrations.RenameModel(
            old_name='Wounique',
            new_name='Wunique',
        ),
        migrations.RenameModel(
            old_name='Woworkwear',
            new_name='Wworkwear',
        ),
    ]
