from django.db import models

class Mancasual(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mancampus(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Manminimal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Manstreet(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mantravel(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mansports(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Manformal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mandandy(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Manunique(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Manworkwear(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

# Woman coordination
class Wocampus(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wosports(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wocasual(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Woformal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Woromantic(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wogirlish(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wostreet(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wofeminine(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wotravel(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wounique(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Woworkwear(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wominimal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wodandy(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

