from django.db import models

class Mcasual(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mcampus(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mminimal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mstreet(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mtravel(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Msports(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mformal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mdandy(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Munique(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Mworkwear(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

# Woman coordination
class Wcampus(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wsports(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wcasual(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wformal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wromantic(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wgirlish(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wstreet(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wfeminine(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wtravel(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wunique(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wworkwear(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wminimal(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)

class Wdandy(models.Model):                 #place to preserve coordinates image
    outer = models.CharField(max_length=30, null=True)
    outercol = models.CharField(max_length=30, null=True)
    top = models.CharField(max_length=30, null=True)
    topcol = models.CharField(max_length=30, null=True)
    bottom = models.CharField(max_length=30, null=True)
    bottomcol = models.CharField(max_length=30, null=True)
    dress = models.CharField(max_length=30, null=True)
    dresscol = models.CharField(max_length=30, null=True)
    url = models.CharField(max_length=100)
